force-app/main/default/objects/Account/fields/Primary_contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/InvoiceMailTriggerTest.cls
@isTest
private class InvoiceMailTriggerTest {

    @isTest
    private static void testingInvoiceMail() {
        Account testAccount = new Account(Name = 'test Account');
        insert testAccount;

        Id standardPricebook = Test.getStandardPricebookId();

        Opportunity testOpportunity = new Opportunity(Name = 'test Opportunity', AccountId = testAccount.Id, CloseDate = Date.today() + 3, Pricebook2Id = standardPricebook, StageName = 'Prospecting');
        insert testOpportunity;

        Contact testContact = new Contact(LastName = 'test Contact', AccountId = testAccount.Id);
        insert testContact;

        testAccount.Primary_contact__c = testContact.Id;
        update testAccount;

        Product2 testProduct = new Product2(Name = 'test Product', IsActive = true);
        insert testProduct;

        PricebookEntry testPricebookEntry = new PricebookEntry(IsActive = true, Product2Id = testProduct.Id, Pricebook2Id = standardPricebook, UnitPrice = 16.24);
        insert testPricebookEntry;

        OpportunityLineItem testLineItem = new OpportunityLineItem(Product2Id = testProduct.Id, OpportunityId = testOpportunity.Id, Quantity = 1, TotalPrice = 16.24);
        insert testLineItem;

        testOpportunity.StageName = 'Closed Won';
        update testOpportunity;

        List<Invoice__c> testInvoice = [SELECT Id FROM Invoice__c WHERE Opportunity__c =: testOpportunity.Id];
        System.assertEquals(1, testInvoice.size(), 'Invoice is being Created');

        System.assertEquals(1, Limits.getEmailInvocations(), 'Emails should be sent');

        
    }
    
}