force-app/main/default/objects/Account/fields/Primary_contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/InvoiceGenartionHandler.cls
public with sharing class InvoiceGenartionHandler {
    public static void sendInvoiceEmail(List<Invoice__c> newRecordList){

        Id opportunityId;
        Id accountId;

        for (Invoice__c customInvoice : newRecordList) {
            opportunityId = customInvoice.Opportunity__c;
            accountId = customInvoice.Account__c;
        }

        
        List<OpportunityLineItem> productList = [SELECT Name, Product2.Name, Quantity, UnitPrice FROM OpportunityLineItem WHERE opportunityId =: opportunityId];


        Id primaryContactId = [SELECT Primary_contact__c FROM Account WHERE Id =: accountId].Primary_contact__c;
        Contact primaryContact = [SELECT Id, Name, Email FROM Contact Where Id =: primaryContactId];


        List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();


        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

        mail.setSubject('Invoice for products purchased');

        List<String> toAddress = new List<String>();
        toAddress.add(primaryContact.Email);
        mail.setToAddresses( toAddress );

        String mailBody = 'Hey ' + primaryContact.Name + ', <br> Here is a list of items purchased by your company: <br><br>';

        mailBody += '<table border="1"><thead><tr><th>Product Name</th><th>Price</th><th>Quantity</th></tr></thead><tbody>';

        for(OpportunityLineItem opp : productList){
            mailBody += '<tr><td>' + opp.Product2.Name + '</td><td>' + opp.UnitPrice + '</td><td>' + opp.Quantity + '</td></tr>';
        }

        mailBody += '</tbody></table><br><br>Thankyou for the Purchase.';
        mail.setHtmlBody(mailBody);
        emailList.add(mail);


        List<Messaging.SendEmailResult> results = Messaging.sendEmail(emailList,false);
        
    }
}